.goreleaser.yaml

Runs locally: 
```bash
goreleaser release --snapshot --clean  
....
• release succeeded after 2m39s
• thanks for using goreleaser!
```

add goreleaser file for governor-api

---

pkg/api/v1alpha1/application_types.go
pkg/api/v1alpha1/applications.go
pkg/api/v1alpha1/authenticated_user.go
pkg/api/v1alpha1/groups.go
pkg/api/v1alpha1/organizations.go
pkg/api/v1alpha1/users.go

not just all enumerated membership

User and group endpoints should return info about direct membership

---

pkg/api/v1alpha1/group_hierarchies.go

- Calculation of added/deleted group members was not properly bound only to the transaction it was running in
- Moved cycle detection step inside the transaction, to take advantage of serializable transactions

Additional group hierarchy transaction fixes

---

internal/dbtools/notification_preferences.go
internal/dbtools/notification_preferences_test.go

Fixed join on soft delete

---

.devcontainer/docker-compose.yml
docker-compose.yml

This reverts commit 5051ad35f9dee5470896de491107670ac3f5838f.
This breaks the dev containers due to `Error: unknown flag: --dangerous-force-http`

Revert "Update oryd/hydra Docker tag to v2 (#32)"

---

db/migrations/00033_group_request_types.sql
internal/dbtools/errors.go
internal/dbtools/hooks.go
internal/dbtools/membership_enumeration.go
internal/models/group_membership_requests.go
internal/models/group_memberships.go
pkg/api/v1alpha1/auth.go
pkg/api/v1alpha1/authenticated_user.go
pkg/api/v1alpha1/errors.go
pkg/api/v1alpha1/group_membership.go
pkg/client/groups.go
pkg/events/v1alpha1/events.go

(expiration to be handled by core addon)
UI, core addon, notification addon PRs incoming.

initial API implementation of admin elevation request and expiration

---

internal/dbtools/membership_enumeration.go

Small bug - admin expiration is always null (concept of admin doesn't exist) on indirect membership and should not be treated as a column to lookup here

admin_expires_at for indirect members is always null

---

internal/dbtools/hooks.go
internal/eventbus/client.go
pkg/api/v1alpha1/errors.go
pkg/api/v1alpha1/extensions.go
pkg/api/v1alpha1/extensions_test.go
pkg/api/v1alpha1/router.go
pkg/api/v1alpha1/testing.go
pkg/client/errors.go
pkg/client/extensions.go
pkg/client/extensions_test.go
pkg/events/v1alpha1/events.go

Operation | Method | URI
-- | -- | --
list | GET | /api/v1alpha1/extensions
create | POST | /api/v1alpha1/extensions
get | GET | /api/v1alpha1/extensions/:slug-or-id
update | PATCH | /api/v1alpha1/extensions/:slug-or-id
delete | DELETE | /api/v1alpha1/extensions/:slug-or-id

[Extend Governor APIs] Extensions Management

---

go.mod
go.sum
internal/dbtools/hooks.go
pkg/api/v1alpha1/extension_resource_definitions.go
pkg/api/v1alpha1/extension_resource_definitions_test.go
pkg/api/v1alpha1/router.go
pkg/client/errors.go
pkg/client/extension_resource_definitions.go
pkg/client/extension_resource_definitions_test.go
pkg/client/governor_test.go
pkg/events/v1alpha1/events.go

Operation | Method | URI
-- | -- | --
list | GET | /api/v1alpha1/extensions/:extension-slug-or-id/erds
create | POST | /api/v1alpha1/extensions/:extension-slug-or-id/erds
get by ID | GET | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:uuid
get by slug | GET | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:slug-singular/:version
update by ID | PATCH | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:uuid
update by slug | PATCH | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:slug-singular/:version
delete by ID | DELETE | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:uuid
delete by slug | DELETE | /api/v1alpha1/extensions/:extension-slug-or-id/erds/:slug-singular/:version

[Extend Governor APIs] Extension Resource Definitions

---

internal/dbtools/hooks.go
pkg/api/v1alpha1/router.go
pkg/api/v1alpha1/sys_extension_resources.go
pkg/api/v1alpha1/sys_extension_resources_test.go
pkg/client/errors.go
pkg/client/sys_extension_resources.go
pkg/client/sys_extension_resources_test.go
pkg/events/v1alpha1/events.go
pkg/jsonschema/unique_constraint.go

| Operation | Method | URI  |
|---|---|---|
| **list** | `GET` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\> |
| **create** | `POST` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\> |
| **get** | `GET` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |
| **update** | `PATCH` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |
| **delete** | `DELETE` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |

[Extend Governor APIs] System Extension Resources

---

internal/dbtools/hooks.go
pkg/api/v1alpha1/errors.go
pkg/api/v1alpha1/router.go
pkg/api/v1alpha1/user_extension_resources.go
pkg/api/v1alpha1/user_extension_resources_test.go
pkg/client/user_extension_resources.go
pkg/client/user_extension_resources_test.go
pkg/jsonschema/unique_constraint.go

- authenticated user resources: `/api/v1alpha1/user/extension-resources`
- admin managing user resources: `/api/v1alpha1/users/:user-id/extension-resources`
| Operation | Method | URI  |
|---|---|---|
| **list** | `GET` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\> |
| **create** | `POST` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\> |
| **get** | `GET` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |
| **update** | `PATCH` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |
| **delete** | `DELETE` | /\<prefix\>/\<extension-slug\>/\<erd-slug-plural\>/\<erd-version\>/\<er-slug-or-id\> |

[Extend Governor APIs] User Extension Resources

---

pkg/jsonschema/compiler_test.go
pkg/jsonschema/unique_constraint.go
pkg/jsonschema/unique_constraint_test.go

An incorrect error message was returned in the `jsonvalidator` when `unique` is defined but `required` is missing

[Small Fix] Enhance JSON Validator Error Messages

---

pkg/jsonschema/compiler.go

Enable content assertion and format assertion for the JSON schema compiler, such that all json payload will be validated properly against the schema.

Add Content Assertions for JSON Schema Compiler

---

pkg/api/v1alpha1/extension_lifecycle.go
pkg/api/v1alpha1/extension_resource_definitions.go
pkg/api/v1alpha1/router.go
pkg/api/v1alpha1/sys_extension_resources.go
pkg/api/v1alpha1/sys_extension_resources_test.go
pkg/api/v1alpha1/user_extension_resources.go

Add a middleware on extension routes to:
- reject any update/create/delete on extension resources whose extension or ERD is disabled
- use `gin.Context` to cache the DB query results throughout a request to reduce duplicate queries

Extension resource lifecycle

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

We pass several ports from this devcontainer compose stack (NATS, Hydra, CRDB...) through to the host using the `ports` option directly in the `docker-compose.yml` file... but we have been omitting the port used by the governor-api app itself from the compose file and instead forwarded it using the `devcontainer.json` `forwardPorts` definition.
This works seamlessly in VSCode, however, `forwardPorts` is unsupported by the devcontainer CLI for anyone using another editor/IDE. The main difference between forwarding a port in the compose file vs. using `forwardPorts` is that `forwardPorts` is necessary for services that only listen on 127.0.0.1 - however, this service listens on 0.0.0.0, thus there is no functional difference here, so proposing this change for QoL/compatibility reasons.

DevContainer QoL change

---

cmd/migrate.go
cmd/serve.go
internal/dbtools/membership_enumeration.go
internal/dbtools/membership_enumeration_test.go
internal/dbtools/notification_preferences_test.go
internal/dbtools/testtools.go
internal/eventbus/client_test.go
pkg/api/v1alpha1/group_hierarchies.go
pkg/api/v1alpha1/user_extension_resources.go
pkg/api/v1alpha1/user_extension_resources_test.go
pkg/client/extensions_test.go
pkg/client/governor_test.go
pkg/client/groups_test.go
pkg/client/hierarchies_test.go
pkg/client/notification_preferences_test.go
pkg/client/notification_targets_test.go
pkg/client/notification_types_test.go
pkg/client/users_test.go
pkg/jsonschema/unique_constraint_test.go

Add checks and tests to ensure that deleted groups are not counted in hierarchical membership resolution or cycle checks

Fix membership bugs with deleted groups in hierarchical relationships

---

pkg/api/v1alpha1/authenticated_user.go

Ensure that the approver group is set before attempting to count the members to see if a membership request should fall back to the Governor global admins or not. This codepath is only hit when a membership request is made to an empty group.

Approver group validity check

---

db/migrations/00038_extensions_resources_admin_groups.sql
internal/models/extension_resource_definitions.go
internal/models/groups.go
pkg/api/v1alpha1/extension_lifecycle.go
pkg/api/v1alpha1/extension_resource_auth.go
pkg/api/v1alpha1/extension_resource_auth_test.go
pkg/api/v1alpha1/extension_resource_definitions.go
pkg/api/v1alpha1/group_membership.go
pkg/api/v1alpha1/router.go

There are two kind of extension resources, `system` and `user` resources, user extension resources are own by each governor user, and currently only `governor-admin`s are allowed to modify system extension resources, this work adds an `admin-group` to each `ERD`s, allow members in these groups to manage their system extension resources

Extension Resources Group Auth

---

pkg/api/v1alpha1/extension_resource_auth.go
pkg/api/v1alpha1/extension_resource_auth_test.go

User auth for system resources should be skipped if there's not `oidc` in scope, which indicates the request is from an oidc client

Small Auth Fix

---

pkg/api/v1alpha1/auth.go
pkg/api/v1alpha1/authenticated_user.go
pkg/api/v1alpha1/extension_resource_auth.go
pkg/api/v1alpha1/group_applications.go
pkg/api/v1alpha1/group_hierarchies.go
pkg/api/v1alpha1/group_membership.go
pkg/api/v1alpha1/groups.go
pkg/api/v1alpha1/users.go

Calls to fetch user/group memberships using dbtools was passing gin.Context as the context instead of the gin.Context's Request.Context() which is where all existing trace context is held.
This updates those calls to pass the request context so the traces are properly related.

fix memberships dbtools traces

---

pkg/api/v1beta1/pagination.go
pkg/api/v1beta1/users.go

We already allow specifying a limit for the query, and while we support cursor-based pagination, we order by ID by default, so offset-based pagination means use-cases like a GetAll SCIM operation which fetch by index are easier to implement.

Add offset to allow for random page access

---

pkg/api/v1beta1/pagination.go
pkg/api/v1beta1/users.go

In the previous PR, the offset value wasn't actually picked out from the query params and placed in the pagination struct.

Make sure and parse offset into the pagination struct

---

internal/dbtools/membership_enumeration_test.go
internal/dbtools/notification_preferences_test.go
internal/dbtools/testing.go
pkg/api/v1alpha1/extension_resource_auth_test.go
pkg/api/v1alpha1/extension_resource_definitions_test.go
pkg/api/v1alpha1/extensions_test.go
pkg/api/v1alpha1/sys_extension_resources_test.go
pkg/api/v1alpha1/user_extension_resources_test.go
pkg/jsonschema/unique_constraint_test.go

The `testserver` package from crdb grabs the latest version of CRDB binary by default, and it breaks all our tests recently. This work adds the ability to pin down a specific version of CRDB for test purposes

Pin Down CRDB Test Server Version

---

internal/backupper/groups.go
internal/backupper/restore.go

The groups DB model has a self-reference (`group->approverGropup`).
This PR implements a simple topological sort to ensure that the dependencies are created before itself.

fix: topological sort before restore
